### ISSUE TITLE
Stops at midnight

### ISSUE THREAD

**Issue by shaggy63** [gerlandotermini/rh-trading-bot#1]
This actually works well, thank you for creating it.
It does appear to just stop executing trades at midnight.  No errors are shown.  I haven't had the chance to dig into it at that level to see what the issue could be.

**Comment by gerlandotermini** [comment]
Hm, not sure why that might be happening. It runs for days at a time on my local server (then the auth key expires). Could it be something related to your server environment killing processes at midnight for some reason? Let me know if you find out more.

**Comment by gerlandotermini** [comment]
Closing this for now. If you still have this issue, feel free to reach out again.
