### ISSUE TITLE
Dependence on profit_percentage in signals

### ISSUE THREAD

**Issue by shaggy63** [gerlandotermini/rh-trading-bot#2]
I may issue a pull request for this if I get to it.

It would be nice if the signals didn't depend on profit_percentage.  I propose profit_percentage to instead be turned into something like take_profit so if the price jumps 20% you can take profit, if not then it will just trade on the signals alone.

**Comment by gerlandotermini** [comment]
Yes, good point. I've been thinking about this myself lately. I'm running the bot on ETH, and with the recent huge swings I wish it had taken the profit before the price went down too much. Feel free to submit a pull request and I'll merge it.
