### ISSUE TITLE
robin_stocks import

### ISSUE THREAD

**Issue by shaggy63** [gerlandotermini/rh-trading-bot#3]
It appears 
import robin_stocks as rh
should be 
import robin_stocks.robinhood as rh

Thanks

**Comment by gerlandotermini** [comment]
I saw that in the documentation ( https://robin-stocks.readthedocs.io/en/latest/quickstart.html#importing-and-logging-in ) however if I do as they say, it returns an error: ModuleNotFoundError: No module named 'robin_stocks.robinhood' I reached out to the developer but they never got back to me

**Comment by gerlandotermini** [comment]
Closing this for now until we get further clarification from the developer
