### ISSUE TITLE
Enable sell of Moving Average cross

### ISSUE THREAD

**Issue by razo559** [gerlandotermini/rh-trading-bot#4]
Is there a way to enable or add the sell of a position if the ticker moving average cross. For example, if the 21 MA on the 5 minute chart crosses the 50 MA on the 5 minute chart, initiate a sell order.

**Comment by gerlandotermini** [comment]
Yes, you can add your own logic to classes/signals.py using any kind of technical analysis . Feel free to submit a pull request once you have the new functions (buy/sell)
