### ISSUE TITLE
Not selling when rsi hit 70 or profit is 1%

### ISSUE THREAD

**Issue by Dragon9090** [gerlandotermini/rh-trading-bot#5]
Hi, I tested your code for the past day or two and it seems like it not selling assets when it pasts the rsi level at 70 or when profit is 1%. The buy is also only buying when rsi is over 50% even if the sell rsi is set to 40. Am I missing something? When is the asset suppose to sell? Thank you and keep up the good work.

**Comment by gerlandotermini** [comment]
Hi thank you for giving my code a try. Which buy/sell signals are you using in your config file? Please keep in mind that all the conditions need to be met, not just the RSI "or" profit.

**Comment by Dragon9090** [comment]
Thank you for your reply. For the config.py file, everything is kept the same as the code you released except trade_enabled=true, robin id/password stored and a reserve set to 10.0. Did I need to change something in the signals.py file?

By the way, when you run the bot are you getting an output of something along the line of "RuntimeError: main thread is not in the main loop" (don't remember the exact wording) in the status.log? If so, I added this line to get rid of it (plt.switch_backend('agg')) after the plt.close( fig ).

**Comment by gerlandotermini** [comment]
The default parameters will work, however remember that all the conditions need to be met. As for the error message, are you launching the bot via the included bash script? What Python version are you using?

**Comment by Dragon9090** [comment]
os: unbuntu
python: tried 3.8.5, 3.6.x, 3.9.x 
I launch the code (./bot.sh start) using terminal and visual studio code. 

As for the default parameters, what are the conditions that need to be met?
If I want to change the parameters what do I need to change? 
Thank you.

**Comment by gerlandotermini** [comment]
You can take a look at the Readme file for a detailed explanation of what each parameter does.

**Comment by Dragon9090** [comment]
Thank you. I think I got it, and I will close this.
