### ISSUE TITLE
Testing new strategy

### ISSUE THREAD

**Issue by Dragon9090** [gerlandotermini/rh-trading-bot#6]
Hi, I'm testing a new simple strategy using the 1 min interval with ema 2 and ema 3 as crossovers. I was wondering if you tried using your bot on 1 min interval. Can Robinhood ban you from making trades too fast?  If the strategy is implemented the bot will most likely trade around 300 times a day. Thank you.

**Comment by gerlandotermini** [comment]
Hi, I've read on online forums that they might ban you if they notice such a high frequency of trades, so I never tried. My setup checks prices every 5 minutes and the crossover parameters trigger a trade every few hours at best, and I usually have no more than 4-5 trades a day. The irony is that high frequency trading is how they make money after all.

**Comment by Dragon9090** [comment]
Interesting, I will update you after more research and see if I get banned.

**Comment by gerlandotermini** [comment]
Please keep us posted

**Comment by Dragon9090** [comment]
How do you change the order from limit order to market order?

**Comment by gerlandotermini** [comment]
It's not that simple. The function that performs the actual buy is 'order_buy_crypto_limit', however the code is designed to work with limit orders (available cash management, how orders are placed, etc). So it's not just a matter of invoking a different API call, the logic should be adjusted as well.

**Comment by Dragon9090** [comment]
I see, thank you for clarifying.

**Comment by Dragon9090** [comment]
Is there a way to make the bid price closer to the marked price?

**Comment by gerlandotermini** [comment]
You could track the "ask" price when retrieving new data, instead of the mark price, in 'get_new_data'

**Comment by Dragon9090** [comment]
Does the code still work if I change the code like this? Thank you. 

def buy_ema_sma_crossover_rsi( self, ticker, data ):
        # Exponential Moving Average Crossover with RSI Filter
        # Buy when Fast-EMA crosses Slow-EMA from below, and RSI > buy threshold (50 suggested)
        #
        # Params: rsi_threshold

        return(        
            # Make sure the data is valid
            not isnan( data.iloc[ -1 ][ ticker + '_EMA_F' ] ) and
            not isnan( data.iloc[ -2 ][ ticker + '_EMA_F' ] ) and
            not isnan( data.iloc[ -1 ][ ticker + '_SMA_F' ] ) and
            not isnan( data.iloc[ -2 ][ ticker + '_SMA_F' ] ) and
            not isnan( data.iloc[ -1 ][ ticker + '_RSI' ] ) and

            # Fast-EMA crossed Slow-EMA from below
            data.iloc[ -2 ][ ticker + '_SMA_F' ] < data.iloc[ -2 ][ ticker + '_EMA_F' ]  and
            data.iloc[ -1 ][ ticker + '_SMA_F' ] >= data.iloc[ -1 ][ ticker + '_EMA_F' ]  and
            
            # RSI above threshold
            data.iloc[ -1 ][ ticker + '_RSI' ] < config[ 'trade_signals' ][ 'buy' ][ 'params' ][ 'rsi_threshold' ]
        )

**Comment by Dragon9090** [comment]
Is there a way to fix the buying power amount not showing after an order is canceled?
